# Generated by Django 5.0 on 2024-05-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_auto_20231004_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverification',
            name='createDate',
            field=models.CharField(default='05/12/24 15:17:05', max_length=300),
        ),
        migrations.AlterField(
            model_name='codeverification',
            name='expiredDate',
            field=models.CharField(default='05/12/24 15:32:05', max_length=300),
        ),
    ]
