# Generated by Django 3.2.12 on 2023-10-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottombanner',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='orderit',
            name='project_description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='proDescription',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
